[tool.poetry]
name = "robusta_chaos"
version = "0.0.1"
description = ""
authors = ["Natan Yellin <aantn@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7.1"

[build-system]
robusta-cli = "^0.10.16"
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
